services:
  api:
    extends:
      file: docker-compose.base.yml
      service: api
    ports:
      - "127.0.0.1:9503:9503"
    command:
      - "-s=session"
    depends_on:
      - mysql
  mysql:
    extends:
      file: docker-compose.base.yml
      service: mysql
    ports:
      - "127.0.0.1:9507:3306"
networks:
  default:
    name: telegram-api-server
